-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Mar 14, 2017 at 01:56 PM
-- Server version: 10.1.13-MariaDB
-- PHP Version: 5.6.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `news`
--

-- --------------------------------------------------------

--
-- Table structure for table `stories`
--

CREATE TABLE `stories` (
  `id` int(10) NOT NULL,
  `type` enum('Top Story','Business','Tech','Trending','Latest','Sport') NOT NULL,
  `headline` varchar(255) NOT NULL,
  `storyText` text NOT NULL,
  `date` date NOT NULL,
  `time` time NOT NULL,
  `author` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `stories`
--

INSERT INTO `stories` (`id`, `type`, `headline`, `storyText`, `date`, `time`, `author`, `title`) VALUES
(1, 'Top Story', 'Apple Pay Launches In Ireland for KBC and Ulster Bank Customers', ' Apple Pay has launched in Ireland, more than two years after it first hit the market.\n\nThe contactless payment service can be used with more recent Apple products to pay for items in-store, online or through apps\n\nThe service requires one of Apple''s newer smartphones - the iPhone 6 and later - or an Apple Watch to be able pay for goods and services in shops. It will also work with newer iPads, the iPod Touch and online through Macs to pay for items online or through apps.\n\nThe first banks to sign up to the service in Ireland are Ulster Bank and KBC, although customers with competing financial institutions can still use the service through Boon, which allows users to add prepaid virtual cards and use them to fund Apple Pay purchases.\n\nPitched as easy to use, secure and private, Apple Pay uses multiple layers of security to ensure payment details are kept private. This security is built into both hardware and software.', '2017-02-21', '07:23:00', 'Sean Moloney', 'Dublin Correspondent'),
(2, 'Business', 'Number of unemployed fell by 40,000 in 2016', 'The number of people in unemployment fell by 40,000 last year, leaving the unemployment rate at 7.1%.\r\n\r\nThis is the lowest unemployment rate since the second quarter of 2008.\r\n\r\nThe figures come from the latest quarterly national household surgery, the official measure of employment and unemployment in the state, carried out by the Central Statistics Office.\r\n\r\nThe number of people in work increased by 3.3% last year, or 65,000. This brought the number of people in employment to 2,048,100.\r\n\r\nThis was the 17th quarter in a row in which employment increased.', '2017-02-21', '09:34:00', 'Ann Canavan', 'Business Reporter'),
(3, 'Business', 'Euro zone business growth fastest since April 2011', 'Euro zone private sector and manufacturing growth unexpectedly accelerated to near a six-year high in February and job creation reached its fastest since August 2007, propelled by strong demand and optimism about the future, a survey found.\r\n\r\nIHS Markit''s euro zone flash composite Purchasing Managers'' Index, seen as a good overall growth indicator, rose sharply to 56.0, the highest since April 2011, from 54.4 in January, confounding expectations for a slight dip to 54.3.\r\n\r\nThe broad-based acceleration, which showed France''s momentum getting close to Germany''s, suggests that if sustained, economic growth could hit 0.6% in the first quarter, according to Markit.\r\n\r\nThat is faster than the 0.4% economists predicted in a Reuters poll earlier this month and suggests an economy in rude health before key national elections this year in France, Germany and the Netherlands.\r\n\r\n"The increased momentum is due to demand growing at a stronger rate, but also that upturn becoming more broad-based," said Chris Williamson, chief business economist at IHS Markit.', '2017-02-21', '13:37:00', 'Liam Mahoney', 'Business Reporter'),
(4, 'Business', 'Kenny warns Ireland may need EU help post-Brexit', 'Taoiseach Enda Kenny has warned that Ireland may need assistance from Europe as a result of Brexit, adding it was "a British policy not an Irish one". \n\nSpeaking at the All-Island Civic Dialogue at Dublin Castle, he said that there was a danger of a retreat to partisan debate in the North following the dissolution of the Assembly.\n\nMr Kenny said: "We must not return to a hard border" and the the most severe impact of Britain leaving the EU could be felt on this island.\n\nFianna Fail leader Micheal Martin said Brexit is the biggest threat since the foundation of the State. \n\nSpeaking as he arrived at Dublin Castle, Mr Martin said people did not understand the gravity of Brexit. ', '2017-02-21', '14:00:00', 'Michael O''Connell', 'Business Reporter'),
(5, 'Tech', 'Accenture to create 300 jobs in Dublin', 'Professional services company Accenture is to create 300 jobs in Dublin.\r\n\r\nThe positions, which will be filled this year, are across a variety of technology and design roles.\r\n\r\n100 of the roles will be in the areas of artificial intelligence, advanced analytics and the Internet of Things.\r\n\r\nThese employees will be based at The Dock - Accenture''s new technology packed innovation and incubation hub in ''Silicon Docks'', around Grand Canal Dock in the city, said to be one of the most intelligent and connected buildings in the world.\r\n\r\nThe facility will be used to develop new services and products for clients in industries such as financial services, retail, life sciences, utilities and consumer goods.', '2017-02-14', '09:30:00', 'Mary O''Brien', 'Technology Reporter'),
(6, 'Tech', 'EU to end barriers to Netflix, streaming sites in 2018', 'The European Union has taken a major step towards allowing people to use online entertainment subscriptions such as Netflix or Amazon Prime all across Europe, according to officials.\r\n\r\nEuropeans spend about one billion nights in other EU countries every year but face a frustrating inability to access subscription services while outside their home country.\r\n\r\nThe European Commission, the bloc''s executive arm which proposed the change, reached a compromise late last night with negotiators from the European Parliament and the European Council of 28 member states, virtually guaranteeing that the measure will succeed.\r\n\r\nOnce formally approved, EU consumers on the move will be able to enjoy entertainment as if at home in early 2018, the commission said.\r\n\r\n"Today''s agreement will bring concrete benefits to Europeans," said Andrus Ansip, the commission''s vice-president for the Digital Single Market.\r\n\r\n"People who have subscribed to their favourite series, music and sports', '2017-02-14', '07:24:00', 'Dermot Lynch', 'Technology Reporter'),
(7, 'Tech', 'Landmark EU-US data privacy court case opens in Dublin', 'The High Court has begun hearing a landmark case with implications for the privacy rights of EU citizens and transatlantic trade.\r\n\r\nThe case marks the first ever involvement by the US government in litigation in the Irish courts, underlining the huge implications for EU-US trade.\r\n\r\nThe Data Protection Commissioner wants the court to refer to the Court of Justice of the EU, issues concerning the transfer of private data by companies from Europe to the US.\r\n\r\nThe case stems from a complaint made in 2013 by Austrian lawyer Max Shrems alleging Facebook''s transfer of his personal data to the US was unlawful.\r\n\r\nIt concerns the transfer of data by Facebook''s Dublin based European Headquarters to its parent company in the US.', '2017-02-15', '15:03:00', 'Conor O''Ryan', 'Technology Reporter'),
(8, 'Trending', 'Drake hits the town with pals after Dublin gigs', 'Canadian rap superstar Drake partied up a storm in Dublin last night after two successful sold-out shows at the 3Arena.\n\nDrake sparked a frenzy in Temple Bar last night as he visited the tourist hot spot with his friends to celebrate his packed-to-capacity gigs in the capital and later posted snaps of him enjoying an array of beverages.\n\n"Got a Hennessy in my hand" as he might sing himself.\n\nAnd this is not the first time the Hotline Bling has enjoyed the festivities of Temple Bar - he first visited three years ago on St Patrick''s Day for a wild night out during his Boy Meets World tour.\n\nThe rapper, whose track One Dance was last year''s best selling single in Ireland after spending ten weeks at number 1 in the charts, shared a number of interesting and moody shots from around the city on Instagram.', '2017-02-21', '14:33:00', 'Frank Malone', 'Dublin Correspondent'),
(9, 'Trending', 'Hidden Figures goes to the moon and beyond', 'Hidden Figures is a missing chapter from history that reminds us how far we''ve come as a society and how there are many walls that still need to come crumbling down.\n\nAmong all the men who restored America''s confidence in the 1960s after NASA launched astronaut John Glenn into orbit, were three exceptional African-American women, who served as the brains during the space race.\n\nSet against the backdrop of the Cold War, Theodore Melfi''s adaptation of Margot Lee Shetterly''s book picks up in 1961 after the Soviets have launched Laika into space.\n\nThe story follows the trio of unsung female heroes working as "computers" for the agency, who defied society''s rules and became pioneers of both their race and sex.\n\nDorothy Vaughan (Octavia Spencer) heads up the division and teaches herself to program the new IBM machine when it arrives at NASA.', '2017-02-17', '09:35:00', 'Patricia O''Casey', 'Entertainment Reporter'),
(10, 'Trending', 'The fries have it. Michael Keaton sizzles in McDonald''s biopic ''The Founder''', 'Given our collective compulsion to lionise business bigwigs, it''ll be interesting to see how Irish audiences feel at the end of The Founder. After all, the canonisation of chieftain types has been hardwired into our DNA for centuries.\r\n\r\nCertainly, Ray Kroc, the man who turned McDonald''s from local landmark into global phenomenon, was way ahead of his time and had a never-say-die attitude that they really should put on the school curriculum. He also left his heart in his desk when it came to getting what he wanted and making money. The beauty of director John Lee Hancock''s film is that you swing between admiration and antipathy before making your mind up.\r\n\r\nWe meet Kroc as "a 52-year-old, over-the-hill, milkshake machine salesman" whose capacity for self-delusion seems roughly the size of the geographical area he covers in his increasingly desperate attempts to flog his wares to drive-in owners around the United States. It''s a life of motel rooms, self-help records and whiskeys at bedtime. And then he gets word that the McDonald brothers (great turns from Nick Offerman and John Carroll Lynch) out in California want six of his mixers. \r\n\r\nThinking it''s a mistake, Kroc calls the siblings, only to find out that their order really is the order. Convinced that his luck has finally changed, Kroc hangs up the phone and puts his foot to the floor to get out West and see for himself what the brothers are doing - and if they''re willing to share.\r\n\r\nAfter Birdman and Spotlight the ''Keatonaissance'' continues here with his portrayal of the little guy who becomes Mr Big. Indeed, it''s hard to think of any other actor who could imbue the character of Kroc with the same charm, clout and cunning. His onscreen battle for control really brings home that there is no sentiment in business, and that the most important part of the American Dream is always the bottom line.', '2017-02-20', '17:00:00', 'Conor Flanagan', 'Entertainment Reporter'),
(11, 'Latest', 'The Weeknd and Mumford & Sons to headline Longitude', 'The Weeknd and Mumford & Sons have been announced as the latest headline acts for Longitude.\r\n\r\nThe music festival is back in Dublin''s Marlay Park on Friday 14 to Sunday 16 of July and the line-up is pretty impressive.\r\n\r\nCanadian singer The Weeknd, who broke streaming records on Spotify in November with single Starboy, will headline the festival on Saturday.\r\n\r\nEnglish rockers Mumford and Sons will take to the main stage on Sunday where they will curate the evening''s performances with their Gentlemen of the Road Stopover.\r\n\r\nJoining The Weeknd and Mumford & Sons are 2016 Mercury Prize winner Skepta, breakout stars of last year Picture This, Brit Award winners Catfish & The Bottlemen and UK singer songwriter and multi-instrumentalist Jack Garratt.', '2017-03-02', '07:06:00', 'Maura O''Sullivan', 'Entertainment Reporter'),
(12, 'Latest', 'Here''s How That Historic Oscars Mix-up Happened', 'There was chaos for a few moments last night when Oscar history was made following the announcement of the wrong winner for Best Picture.\r\n\r\nFamous leading man Warren Beatty began, "For Best Picture..." And then he looked at the envelope, paused and looked at Faye Dunaway. Dunaway laughed, called him impossible and announced La La Land as the winner. The stage immediately filled with the cast and crew - but also with Oscar producers.\r\n\r\nWhen La La Land producer Jordan Horowitz was advised of the mistake, he explained, "I''m sorry, there''s a mistake. Moonlight, you guys won best picture." Amid the confusion, producer Marc Platt reiterated, "This is not a joke. They read the wrong thing."\r\n\r\nHorowitz flashed the card showing the winning movie to the audience. And with that, the Moonlight cast crew made their way to the stage.\r\n\r\nLater, host Jimmy Kimmel joked, "Personally, I blame Steve Harvey for this." Harvey made history at the 2015 Miss Universe pageant when he misread the winner as Miss Colombia when it was actually Miss Philippines.', '2017-02-27', '06:49:00', 'Kelly Phillips', 'Entertainment Reporter'),
(13, 'Latest', 'PwC partners out of the picture after Oscar mix-up', 'The two PwC partners at the heart of the Oscar fiasco that led to the wrong film briefly being named best picture have been told by the Academy of Motion Picture Arts & Sciences that they will not be allowed to attend future ceremonies.\r\n\r\nThe decision, which Academy president Cheryl Boone Isaacs confirmed in an interview with the Associated Press, is the latest reputational blow to PwC, which has been hit by a wave of criticism since Sunday night’s on-air mistake.\r\n\r\nPwC has overseen Oscars voting and award-giving for 83 years, but the Academy is reviewing its long relationship with the accountancy firm, according to a spokeswoman. “The review began on Sunday night,” she said.\r\n\r\nThe mistake occurred when Brian Cullinan, chairman of PwC’s US board, gave the wrong winner’s envelope to Warren Beatty, who, together with Faye Dunaway, was due to present the Oscar for best picture.\r\n\r\nAfter a brief moment of confusion, Mr Beatty and Ms Dunaway announced La La Land as the best picture winner. Moments later, as the movie’s producers were giving emotional thank you speeches, they were interrupted and told that a mistake had been made, and that Moonlight was the best picture winner.\r\n', '2017-03-02', '07:23:00', 'Matthew Garrahan', 'US Correspondent'),
(14, 'Sport', 'Arsene Wenger ''not looking for jobs'' amid Barcelona speculation', 'Arsene Wenger insists he is not looking for other jobs despite a vacancy opening up at Barcelona and his Arsenal future being up in the air.\r\n\r\nThe 67-year-old has said he will make a decision on whether to extend his 20-year tenure with the Gunners either this month or next and revealed in February that he will continue his managerial career even if he does not sign a new deal at the Emirates Stadium.\r\n\r\nThat led to Wenger being linked to the Barcelona post after current coach Luis Enrique announced on Wednesday night that he would be leaving in the summer in order to take a break from the game.\r\n\r\nBut the Frenchman said his preference would be to remain at Arsenal rather than negotiate a move to the Catalan giants or any other potential suitor.\r\n\r\nAsked whether he would be interested in a move to the Nou Camp, he said: "No, my preference has always been the same and will remain the same.', '2017-03-02', '10:35:00', 'Dermot O''Connell', 'Sports Reporter'),
(15, 'Sport', 'Paddy Jackson signs new Ulster deal', 'Paddy Jackson has committed his future to Ulster by signing a deal to keep him at the Kingspan Stadium until 2019.\r\n\r\nThe out-half has been a vital cog in the Ulster side, with 2 tries and 111 kicked points this season, contributing to a career total in excess of 800 points.\r\n\r\nJackson also started Ireland''s first two Six Nations games this season and has offered regular competition to Johnny Sexton.\r\n\r\n"I''m delighted to be staying on at Ulster Rugby for at least another two years. It is such a proud moment for myself and my family," said Jackson.\r\n\r\n"Every time I pull on the Ulster jersey it is something that I don''t want to take for granted and I hope to continue to grow as a player and contribute to this team in a positive way.\r\n\r\n"I believe that the pillars for success are in place here at Ulster with a quality squad and management team. I am hugely excited by the challenges that lie ahead and I''d like to thank everyone who has helped me to this point in my career.”', '2017-03-01', '15:34:00', 'Kieran Callaghan', 'Sports Reporter'),
(16, 'Sport', 'Football stars battle it out in live shooting contest for Nike', 'Nike has held a live footballing event, pitching big name footballers in a battle of the finishers in London.\n\nStrike Night received more than half a million views on Facebook and featured a series of big names.\n\nThe promotional event, the first of its kind, tasked players to receive a ball and finish it beyond goalkeepers from Nike''s academy to win the evening’s trophy belt.\n\nWith five attempts in each round, points were awarded for scoring with more given for getting putting the ball “top-bins” – in the top corner.\n\nMeanwhile judges Ian Wright, Didier Drogba, Grime MC AJ Tracey and rapper Santan Dave gave bonus points to the players for their finishes, taking note of the quality and flair of their goals.\n\nFinally, those viewing on Facebook decided the winners, with their interaction with the video gifting the players points.', '2017-03-01', '21:34:00', 'Ossian O''Casey', 'Sports Reporter');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `stories`
--
ALTER TABLE `stories`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `stories`
--
ALTER TABLE `stories`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=29;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
